# Generated by Django 5.0 on 2024-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('NameUser', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=60)),
            ],
        ),
    ]
