# Generated by Django 5.0 on 2024-01-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=60)),
                ('Country', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('Price', models.FloatField()),
                ('Days', models.CharField(max_length=60)),
                ('Night', models.CharField(max_length=60)),
                ('Description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
