# Generated by Django 5.0 on 2024-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Description',
            field=models.CharField(max_length=2000),
        ),
    ]
