# Generated by Django 5.0 on 2024-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_package_image2_package_image3_package_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='Image2',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='Image3',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='Image4',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='Image5',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='Image6',
            field=models.ImageField(upload_to='image'),
        ),
    ]
