# Generated by Django 5.0 on 2024-01-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_package_image6'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='EndDate',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='package',
            name='StartDate',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
