# Generated by Django 5.0 on 2024-01-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_package_image5_remove_package_image6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Description',
            field=models.TextField(max_length=2000),
        ),
    ]
