# Generated by Django 5.0 on 2024-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Description',
            field=models.CharField(max_length=2000),
        ),
    ]
