# Generated by Django 5.0 on 2024-01-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_bookpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpackage',
            old_name='pid',
            new_name='Pid',
        ),
        migrations.RenameField(
            model_name='bookpackage',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='bookpackage',
            old_name='total_person',
            new_name='Total_Person',
        ),
        migrations.RenameField(
            model_name='bookpackage',
            old_name='total_price',
            new_name='Total_Price',
        ),
        migrations.RenameField(
            model_name='bookpackage',
            old_name='uid',
            new_name='Uid',
        ),
    ]
