# Generated by Django 5.0 on 2024-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_pid_bookpackage_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpackage',
            name='Total_Person',
            field=models.IntegerField(default=1),
        ),
    ]
