# Generated by Django 5.0 on 2024-01-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_book_package_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_package',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Phone_No',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Place',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Total_Person',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='Total_Price',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='uid',
        ),
    ]
