# Generated by Django 5.0 on 2024-01-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_book_package_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_package',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='book_package',
            name='uid',
        ),
    ]
