# Generated by Django 5.0 on 2024-01-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_book_package_pid_remove_book_package_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Phone_No', models.CharField(max_length=60)),
                ('Request', models.CharField(max_length=200)),
            ],
        ),
    ]
